FILES = \
	dk_error.o \
	bigdata_comp.o \
	bigdata_decomp.o \
	smalldata.o \
	dkcchr.o \
	dkcgbc.o \
	dkl_tilemap.o \
	dkl_tileset.o \
	gbahuff20.o \
	gbahuff50.o \
	gbahuff60.o \
	gba_lz77.o \
	gba_rle.o \
	gba_auto.o \
	gb_printer.o \
	dk_comp_lib.o \
	dk_wasm_libc.o \
	dk_wasm_api.o \
	qsort.o

CC     = clang
OUTPUT = dkcomp.wasm
WASM   = --target=wasm32 -nostdlib -DBUILD_WASM 
CFLAGS = $(WASM) -Wall -Wextra -Werror
LDFLAGS= $(WASM) -Wl,--no-entry

all: CFLAGS += -O2 -flto
all: $(FILES)
	$(CC) $(LDFLAGS) $(CFLAGS) -o $(OUTPUT) $(FILES)
	wasm-strip $(OUTPUT)

clean:
	rm $(FILES) $(OUTPUT)
